### ISSUE TITLE
Getter and setter for parameters in Feedstock, Pretreatment, EnzymaticHydrolysis and Bioreactor classes 

### ISSUE THREAD

**Issue by olgadoronina** [NREL/VirtualEngineering#15]
Add getters & setters to 
 
  - add validation parameters bounds (check that a user assigns a parameter in the allowed interval) 
  - automatically convert units for some parameters when getting and setting a value.
  - automatically rewrite the parameter's YAML file  

TODO:

- [x] Write getter/setter functions
- [x] Update the sweep function in the optimization notebook and verify the correctness
- [x] Update Optimization class
- [x] Update the optimization function in the notebook and verify the correctness

**Comment by olgadoronina** [comment]
The user doesn't need to know about unit conversion, but the YAML file stores converted values. This may confuse the user if one looks at the parameter file

**Comment by eyoung55** [comment]
Made a new issue so we don't lose track of the unit conversion, can this issue be closed now?
